[versions]
agp = "8.6.0"
androidx-activity = "1.9.2"
androidx-monitor = "1.7.2"
androidx-splashscreen = "1.0.1"
androidx-uiTest = "1.7.1"
build-android-compileSdk = "35"
build-android-minSdk = "24"
build-android-targetSdk = "35"
build-javaVersion = "VERSION_21"
build-jvmTarget = "21"
compose = "1.7.0-beta01"
compose-screenshot = "0.0.1-alpha06"
detekt = "1.23.7"
google-firebase-bom = "33.2.0"
google-ksp = "2.0.20-1.0.25"
google-services = "4.4.2"
javax-json = "1.1.4"
jetbrains-lifecycle = "2.8.1"
jetbrains-navigation = "2.8.0-alpha09"
koin = "4.0.0-RC2"
koin-ksp = "1.4.0-RC4"
kotlin = "2.0.20"
kotlinx-coroutines = "1.9.0-RC.2"
kotlinx-serialization = "1.7.2"
ktlint = "1.3.1"
moko = "0.18.0"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-uiTest" }
androidx-monitor = { group = "androidx.test", name = "monitor", version.ref = "androidx-monitor" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-splashscreen" }
androidx-testManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-uiTest" }
google-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "google-firebase-bom" }
javax-json-api = { module = "javax.json:javax.json-api", version.ref = "javax-json" }
javax-json-glassfish = { module = "org.glassfish:javax.json", version.ref = "javax-json" }
jetbrains-compose-compiler-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
jetbrains-compose-plugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose" }
jetbrains-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "jetbrains-lifecycle" }
jetbrains-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "jetbrains-navigation" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-ksp" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-ksp" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktlint-cli = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlint" }
moko-permissions-compose = { module = "dev.icerock.moko:permissions-compose", version.ref = "moko" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-screenshot = { id = "com.android.compose.screenshot", version.ref = "compose-screenshot"}
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "google-ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
